import os
import cv2
import albumentations as A
from tqdm import tqdm
from pathlib import Path

# ================= CONFIGURATION =================
# Path to the data generated by your previous script
INPUT_DIR = os.path.join("data", "cropped_wells")
# Where to save the upsampled data
OUTPUT_DIR = os.path.join("data", "augmented_wells")

# How many new versions to create per original image
AUGMENTATION_FACTOR = 4  
# =================================================

def get_augmentation_pipeline():
    """
    Defines the transformations. 
    For circular wells (petri dish/colony), orientation often doesn't matter,
    so Flips and Rotations are mathematically safe.
    """
    return A.Compose([
        A.HorizontalFlip(p=0.5),
        A.VerticalFlip(p=0.5),
        A.RandomRotate90(p=0.9),
    ])

def process_augmentation():
    transform = get_augmentation_pipeline()
    
    # Walk through the directory structure created by your crop script
    image_files = []
    for root, dirs, files in os.walk(INPUT_DIR):
        for file in files:
            if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                image_files.append(os.path.join(root, file))

    print(f"Found {len(image_files)} original images. Generating {AUGMENTATION_FACTOR} variations each.")
    print(f"Total expected images: {len(image_files) * (AUGMENTATION_FACTOR + 1)}")

    for img_path in tqdm(image_files, desc="Augmenting"):
        try:
            # 1. Read Image
            image = cv2.imread(img_path)
            if image is None:
                continue
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # Albumentations uses RGB

            # 2. Replicate directory structure in output
            # Get relative path (e.g., "Plate_Type_A/plate_1/image.jpg")
            rel_path = os.path.relpath(img_path, INPUT_DIR)
            parent_folder = os.path.dirname(rel_path)
            
            save_folder = os.path.join(OUTPUT_DIR, parent_folder)
            os.makedirs(save_folder, exist_ok=True)
            
            base_name = os.path.splitext(os.path.basename(img_path))[0]

            # 3. Save Original (Optional, but usually you want the original too)
            original_save_path = os.path.join(save_folder, f"{base_name}_orig.jpg")
            cv2.imwrite(original_save_path, cv2.cvtColor(image, cv2.COLOR_RGB2BGR))

            # 4. Generate Augmentations
            for i in range(AUGMENTATION_FACTOR):
                augmented = transform(image=image)['image']
                
                # Convert back to BGR for OpenCV saving
                augmented_bgr = cv2.cvtColor(augmented, cv2.COLOR_RGB2BGR)
                
                save_name = f"{base_name}_aug_{i}.jpg"
                cv2.imwrite(os.path.join(save_folder, save_name), augmented_bgr)

        except Exception as e:
            print(f"Error augmenting {img_path}: {e}")

if __name__ == "__main__":
    process_augmentation()